import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="mb-6 text-2xl font-bold">Welcome to Your Tool Dashboard</h1>
        <div className="flex h-screen">
          <main className="flex-1 bg-gray-100 p-8">
            <header className="mb-8"></header>
            <section>{children}</section>
          </main>
        </div>
      </body>
    </html>
  );
}
