import TopNav from '@Components/navbar/TopNav';
import Providers from '@Components/Providers';
import { Link } from '@nextui-org/react';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'NextMatch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  ...props
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(props);
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <div className="mt-1 flex gap-4 border border-success">
            <Link href="/zip-images" underline="hover" color="primary">
              View Zip Images
            </Link>
            <Link href="#" underline="hover">
              Hover
            </Link>
            <Link href="#" underline="always">
              Always
            </Link>
            <Link href="#" underline="active">
              Active
            </Link>
            <Link href="#" underline="focus">
              Focus
            </Link>
          </div>
          <main className="container mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
// tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge
