import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <aside className="w-64 bg-gray-800 text-white p-4">
            <nav>
              <ul>
                <li>
                  <a
                    href="/tool1"
                    className="block py-2 px-4 rounded hover:bg-gray-700"
                  >
                    Tool 1
                  </a>
                </li>
                <li>
                  <a
                    href="/tool2"
                    className="block py-2 px-4 rounded hover:bg-gray-700"
                  >
                    Tool 2
                  </a>
                </li>
                {/* Add more navigation items here */}
              </ul>
            </nav>
          </aside>
          <main className="flex-1 bg-gray-100 p-8">
            <header className="mb-8">
              <h1 className="text-3xl font-bold">Dashboard</h1>
            </header>
            <section>{children}</section>
          </main>
        </div>
      </body>
    </html>
  );
}
