packages:
  # Match the actual project structure in rush.json
  - "backend/**"
  - "frontend/**"
  - "APIs/**"
  - "infrastructure/**"
  - "library/**"
  - "services/**"
  - "examples/**"
  # exclude test directories
  - "!**/test/**"
