FROM nvidia/cuda:12.3.2-devel-ubuntu22.04

# Update the package repository and install system dependencies
RUN apt-get update && apt-get install -y \
  python3-pip \
  python3-dev \
  && rm -rf /var/lib/apt/lists/*

# Upgrade pip to the latest version
RUN pip --no-cache-dir install --upgrade pip

# Set the working directory in the Docker image
WORKDIR /app

# Copy the requirements file into the container's work directory
COPY ./ComfyUI/ /app/

# Install Python dependencies from requirements.txt
RUN pip --no-cache-dir install -r requirements.txt
# Set an argument for the default port number
ARG DEFAULT_PORT=8383

# Set the default environment variable for the port, which can be overridden at runtime
ENV PORT=$DEFAULT_PORT

# Set the CUDA_VISIBLE_DEVICES environment variable
# ENV CUDA_VISIBLE_DEVICES=0,1

EXPOSE ${DEFAULT_PORT}

RUN python3 --version
# Continue with the rest of your Dockerfile...
# The command to run your application
# The command to run your application --cuda-device 1
CMD ["sh", "-c", "python3 main.py --auto-launch --use-pytorch-cross-attention --port ${PORT} --force-fp16"]
